const {readFileSync} = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const P = {};
vm.createContext(P);
vm.runInContext(readFileSync(require('node:path').join(__dirname,'../app/Physics.js'),'utf8'), P);
const bounds={width:1920,floor:1020};
const platform={id:'window:a:0',left:400,right:1000,top:400};
function advance(s, ps, seconds=3) { for(let i=0;i<seconds*144;i++) s=P.step(s,ps,bounds,1/144); return s; }
let s=Object.assign(P.initial(500,1020),{y:10,grounded:false,support:''});
s=advance(s,[platform]);
assert.equal(s.support,platform.id); assert.equal(s.y,272); assert.equal(s.vy,0);
s=P.step(s,[{...platform,left:500,right:1100,top:450}],bounds,1/144);
assert.equal(s.x,600); assert.equal(s.y,322);
s=advance(s,[]); assert.equal(s.support,'floor'); assert.equal(s.y,892);
s=advance({...P.initial(100,1020),vx:1200,vy:-1400,grounded:false,support:''},[]);
assert.ok(s.x>=0 && s.x<=1792); assert.equal(s.support,'floor');
s=P.jumpTo(P.initial(100,1020),platform,1920);
s=advance(s,[platform]); assert.equal(s.support,platform.id);
const notif={id:'notification:1:0',left:1400,right:1840,top:860};
s=advance(P.jumpTo(P.initial(100,1020),notif,1920),[notif]); assert.equal(s.support,notif.id);
s=advance(s,[]); assert.equal(s.support,'floor');
const mon={id:0,x:1920,y:0,activeWorkspace:{id:2},specialWorkspace:{id:0}};
const client={address:'a',mapped:true,hidden:false,visible:true,monitor:0,workspace:{id:2},at:[2200,400],size:[600,400],focusHistoryID:1};
let ps=P.windowPlatforms([client],mon,1920,1080,[]);
assert.equal(ps[0].left,280); assert.equal(ps[0].top,400);
assert.equal(P.windowPlatforms([{...client,workspace:{id:3}}],mon,1920,1080,[]).length,0);
assert.equal(P.windowPlatforms([{...client,hidden:true}],mon,1920,1080,[]).length,0);
assert.equal(P.windowPlatforms([{...client,at:[2200,20]}],mon,1920,1080,[]).length,0);
assert.equal(P.windowPlatforms([{...client,fullscreen:2}],mon,1920,1080,[]).length,0);
ps=P.windowPlatforms([client,{...client,address:'b',at:[2400,200],size:[200,500],floating:true,focusHistoryID:0}],mon,1920,1080,[]);
assert.equal(ps.length,3); assert.equal(ps[1].right,480); assert.equal(ps[2].left,680);
assert.equal(P.windowPlatforms([client],{...mon,specialWorkspace:{id:-99}},1920,1080,[]).length,0);
console.log('PASS: window/popup landing, moving and closing support, throws, automatic jumps, monitor coordinates, workspaces, hidden/fullscreen filtering and occlusion.');
